config/routes.rb
ProjetWeb::Application.routes.draw do

  devise_for :admins
  devise_for :users
  get "/test" => "test#index"

  get "/" => "accueil#login"

  get"/about/us" => "about#us"

  get "/" => "internships#search"
  get "/users/index" 
  get "/users/validate" => "users#validate"

 

  get "internships/show_all" => "internships#show_all"
  get "companies/show_all" => "companies#show_all"
  post "internships/search" => "internships#search"
  get "internships/result" 
  post "internships/signal" 
  get "internships/unsignal"

  root 'internships#index'

  resources :internships
  resources :companies

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Stagiie
    %link{href: "app/assets/stylsheets/bootstrap-3.1.1-dist/css/bootstrap.min.css", rel: "stylesheet"}/
    %link{href: "app/assets/stylsheets/flat-ui.css", rel: "stylesheet"}/
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{href: "app/assets/stylesheets/style.css", rel: "stylesheet"}
  %body
    %nav.navbar.navbar-inverse{role: "navigation"}
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %a.navbar-brand{href: "/"} Stagiie
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            
            %li.dropdown
              %a.dropdown-toggle{href:"", "data-toggle"=>"dropdown", id:"text-nav"} 
                ="Stage"
              %ul.dropdown-menu
                %li
                  %a{href:"/internships/new", id:"text-dropdown"} 
                    ="+ Stage"
                %li
                  %a{href:"/internships/show_all", id:"text-dropdown"} 
                    ="Voir tous"

            %li.dropdown
              %a.dropdown-toggle{href:"", "data-toggle"=>"dropdown", id:"text-nav"} 
                ="Entreprise"
              %ul.dropdown-menu
                %li
                  %a{href:"/companies/new", id:"text-dropdown"} 
                    ="+ Entreprise"
                %li
                  %a{href:"/companies/show_all", id:"text-dropdown"} 
                    ="Voir toutes"
            %li
              %a{href: "", "data-target" => ".bs-example-modal-lg", "data-toggle" => "modal", id:"text-nav"} A propos
              .modal.fade.bs-example-modal-lg{"aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", role: "dialog", tabindex: "-1"}
                .modal-dialog.modal-lg
                  .modal-content
                    .modal-header
                      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
                      %h4 
                        Stagiie
                        %small 
                          Pour le partage d'expériences entre iiens
                    .modal-body
                      %h6 Quel est le but de ce site ?
                      %p Cette application web est destinée à l'ensemble des étudiants de l'ENSIIE, école nationale supérieure d'informatique pour l'industrie et l'entreprise. Elle permet aux étudiants qui recherchent un stage d'été d'obtenir des informations, des exemples de ce qu'il est possible de faire dans un stage ou encore d'avoir accès à une base de données d'entreprises qui ont des relations avec l'école.               
                      %h6 Pourquoi ce site ?
                      %p Ce site fait l'objet d'un sujet de programmation web au cours du semestre 2 de formation. Il est développé en Ruby on Rails 4, s'appuie sur une base de donnée PostgreSQL 9.1 et utilise le template Twitter Bootstrap 3 modifié.
                      %h6 L'équipe
                      %p La dream team chargée du développement est consituée de 2 étudiants :
                      %ul
                        %li
                          %p Aurélie Pallas
                        %li
                          %p Olivier Staub
                      %p Dernière maj du site le 11 avril 2014

                    .modal-footer
                      %button.btn.btn-danger{"data-dismiss" => "modal", type: "button"} Fermer

          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li 
                = form_tag("/internships/search", method: "post", class: "navbar-form") do
                  %div
                    %input.form-control{type: "text", name: "mot"}
                    %button.btn.btn-inverse{type: "submit"}
                      Rechercher
              %li
                = link_to current_user.firts_name+' '+current_user.name, edit_user_registration_path, :class => 'navbar-link', id:"text-nav-right"
              %li
                \#{link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class => 'navbar-link', id:"text-nav-right"}
            - else 
              - if admin_signed_in?
                %li
                  =link_to current_admin.firts_name+' '+current_admin.name, edit_admin_registration_path, :class => 'navbar-link', id:"text-nav-right"
                %li
                  \#{link_to "Se déconnecter", destroy_admin_session_path, method: :delete, :class => 'navbar-link', id:"text-nav"}
              - else
                %li
                  = link_to "S'inscrire", new_user_registration_path, :class => 'navbar-link', id:"text-nav-right"
                %li
                  \#{link_to "Se connecter", new_user_session_path, :class => 'navbar-link', id:"text-nav-right"}          
    
    .container
      .titre
        %h4
          Stagiie
          %small Venez partager l'expérience de la machine à café
      - if flash[:alert]
        .alert.alert-success.alert-dissmissable
          %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
          = flash[:alert]
    
    .container
      #body
        = yield

app/views/layouts/hc.html.haml
  .container
    %h5
      ="Hello stranger"
      %small
        ="veuillez vous connecter ou vous inscrire pour accéder au site !"
    #banierehc
      .row
        .col-md-3
          .center
            %img{alt: "Calendar", src: "/images/icons/svg/calendar.svg"}
        .col-md-3
          .center
            %img{src: "/images/icons/svg/compas.svg"}
        .col-md-3
          .center
            %img{src: "/images/icons/svg/pencils.svg"}
        .col-md-3
          .center
            %img{src: "/images/icons/svg/retina.svg"}
      .row
        .col-md-3
          .center
            %h6 Vous cherchez un stage et vous manquez d'inspiration ?        
        .col-md-3
          .center
            %h6 Vous ne connaissez pas beaucoup d'entreprises de la région ?
        .col-md-3
          .center
            %h6 Vous êtes un ancien qui souhaite contribuer au réseau des iiens ?
        .col-md-3
          .center                         
            %h6 Inscrivez-vous, découvrez et partagez !
    .row
      .col-md-6
        #btnhc_connection
          =button_to "Se connecter", new_user_session_path, class: "btn btn-primary btn-lg", :method => "get"
      .col-md-6
        #btnhc_inscription
          =button_to "S'inscrire", new_user_registration_path, class: "btn btn-inverse btn-lg", :method => "get" 